apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 01-namespace.yaml
  - 02-configmaps.yaml
  - 03-services.yaml
  - 04-persistent-volumes.yaml
  - 05-spark-master.yaml
  - 06-spark-workers.yaml
  - 07-minio.yaml
  - 08-jupyter.yaml
  - 09-ingress.yaml